[package]
name = "zai-rmcp-test"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
publish = false

[dependencies]
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0.102"
rmcp = { version = "3.0.0", features = [
    "client",
    "transport-streamable-http-client-reqwest",
] }
zai-rs = { path = "../../../", features = ["rmcp-kits"] }
