[package]
name = "mcp_server"
version = "0.1.5"
edition = "2024"
publish = false

[dependencies]
rmcp = { version = "2.2.0", features = [
    "server",
    "macros",
    "client",
    "transport-io",
    "transport-streamable-http-server",
    "auth",
    "elicitation",
    "schemars",
] }
tokio = { version = "1.52.3", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "io-std",
    "signal",
] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
anyhow = "1.0.102"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = [
    "env-filter",
    "std",
    "fmt",
] }
axum = { version = "0.8.9", features = ["macros"] }
schemars = "1.2.1"

[dev-dependencies]
tokio-stream = { version = "0.1.18" }
tokio-util = { version = "0.7.18", features = ["codec"] }
